AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  This template create a EC2 Instance with a security 
  Group allowing SSH on port 22 from any IP address

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro

Resources:
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Securtiy Group allowing SSH connection to EC2 Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-05d72852800cbf29e
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref mySecurityGroup

Outputs:
  InstanceId:
    Description: InstanceId of myEC2Instance
    Value: !Ref myEC2Instance
  PublicIp:
    Description: Public IP address of the EC2 Instance
    Value: !GetAtt
           - myEC2Instance
           - PublicIp 